実装：TechProfileEdit
geekcamp2023-vol2-team31/frontend-2 pull request #37
Opened 2023-06-15 15:51 UTC by satojin219

close #23 
close # 22
<img width="948" alt="スクリーンショット 2023-06-18 21 40 28" src="https://github.com/geekcamp2023-vol2-team31/frontend-2/assets/81739310/53e863f0-2611-4e5c-a322-55ec981e5980">

2023-06-18 12:42 UTC, satojin219 commented
技術を取得するAPIが未実装なので、状態の記述がありません、、スクショのものはハードコードです、、

2023-06-19 10:29 UTC, bildeneins requested changes
iconについて、各コンポーネントに手を加えずにスタイルを当てるのはどうでしょうか？
とりあえずdeleteIconについてsuggestしてみました。
また、各カラムについて、対応するアイコンのみactiveにするんだったと思います（例: "完全に理解した"欄では旗アイコンだけ強調）。ただ、この部分についてはfigmaに反映されていないもののデザインを変える話をしていた気もします。

2023-06-19 10:29 UTC, bildeneins commented on src/assets/deleteIcon.tsx
> +      fill="fill"
```suggestion
      fill="none"
```

2023-06-19 10:29 UTC, bildeneins commented on src/components/Profile/TechProfileEditor/TechProfileEditor.module.scss
> +}
```suggestion
}

.icon {
  fill: gray;
}

.active {
  fill: black;
}
```

2023-06-19 10:29 UTC, bildeneins commented on src/components/Profile/TechProfileEditor/TechProfileEditor.tsx
> +                  <DeleteIcon className={style.active} />
```suggestion
                  <DeleteIcon className={style.icon} />
```

2023-06-21 14:37 UTC, bildeneins approved these changes

2023-06-21 14:40 UTC, bildeneins commented on src/components/Profile/TechProfileEditor/TechProfileEditor.tsx
> +                  <FlagIcon className={`${style.icon} ${style.button}`} />
```suggestion
                  <FlagIcon className={`${style.icon} ${style.button}`} />
```
```suggestion
                  <FlagIcon className={`${style.icon} ${style.button} ${style.active}`} />
```

2023-06-22 06:09 UTC, merged